![image.png]()

In [ ]:
# Importing Pandas
import pandas as pd

In [ ]:
# Creating Series
# One Dimentional
s = pd.Series([20, 30, 50])
s

0    20
1    30
2    50
dtype: int64

In [ ]:
# Creating DataFrame
df = pd.DataFrame({
    'Names':['John', 'James', 'Samuel', 'Peter'],
    'Ages':[18, 13, 17, 16],
    'Location':['Rivers', 'Jos', 'Enugu', 'Abuja']
}, index=[1,2,3,4])

df

    Names  Ages Location
1    John    18   Rivers
2   James    13      Jos
3  Samuel    17    Enugu
4   Peter    16    Abuja

### Creating DataFrames from Sequencies

In [ ]:
# List
data = [1, 2, 3, 4, 5, 6, 7]

# Creating DataFrame
df = pd.DataFrame(data)
df

   0
0  1
1  2
2  3
3  4
4  5
5  6
6  7

In [ ]:
# Dictionary
dictionary = pd.DataFrame({
    'Names':['John', 'James', 'Samuel', 'Peter'],
    'Ages':[18, 13, 17, 16],
    'Location':['Rivers', 'Jos', 'Enugu', 'Abuja']
})

# Creating DataFrame
df = pd.DataFrame(dictionary)
df

    Names  Ages Location
0    John    18   Rivers
1   James    13      Jos
2  Samuel    17    Enugu
3   Peter    16    Abuja

In [ ]:
# Series
data = pd.Series([20, 30, 20, 30, 50, 50])

series_df = pd.DataFrame(data)
series_df

    0
0  20
1  30
2  20
3  30
4  50
5  50

In [ ]:
# Numpy Array
import numpy as np

arr = np.array([[10, 30, 45], [2, 4, 5]])

df=pd.DataFrame({
    'Salary':arr[0],
    "ID":arr[1]
})

df

   Salary  ID
0      10   2
1      30   4
2      45   5

### Loading and Saving Data to file

#### Handling Excels

In [ ]:
# Loading XlSX Files
excel_df = pd.read_excel("/content/drive/MyDrive/LOCTEC/DAWP 2023/Datasets/for excel/Data-for-Practice.xlsx")
excel_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Excel Data for Practice Free Download,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Sales Rep,Shift,Cost Price,Selling Price,Profit,Profit %,Commission,Weekday
3,NaN,2022-07-01 00:00:00,Ben,Night,1112.94,1288,NaN,NaN,NaN,NaN
4,NaN,2022-07-01 00:00:00,Jacob,Day,1095.5,1250.75,NaN,NaN,NaN,NaN

In [ ]:
# Saving as CSV files
excel_df.to_csv("sample.csv")

In [ ]:
# Saving CSV without Index
excel_df.to_csv("sample2.csv", index=False)

In [ ]:
# Saving as EXCEL files
excel_df.to_excel("sample.xlsx")

#### Handling JSON

In [ ]:
# Loading JSON file
JSON_df = pd.read_json("/content/drive/MyDrive/LOCTEC/DAWP 2023/Datasets/for json/CA_category_id.json")
JSON_df.head()

,kind,etag,items
0,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
1,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
2,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
3,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."
4,youtube#videoCategoryListResponse,"""ld9biNPKjAjgjV7EZ4EKeEGrhao/1v2mrzYSYG6onNLt2...","{'kind': 'youtube#videoCategory', 'etag': '""ld..."

In [ ]:
# Saving df file as JSON
JSON_df.to_json("new_JSON.json")

#### Handling CSV

In [ ]:
# CSV files
df = pd.read_csv("/content/drive/MyDrive/LOCTEC/DAWP 2023/Datasets/Blood Donation/transfusion.csv")
df

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0
...,...,...,...,...,...
743,23,2,500,38,0
744,21,2,500,52,0
745,23,3,750,62,0
746,39,1,250,39,0
747,72,1,250,72,0

### Pandas Functions

In [ ]:
# Checking Data Type
type(df)

pandas.core.frame.DataFrame

In [ ]:
# Displaying First Rows
df.head()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
0,2,50,12500,98,1
1,0,13,3250,28,1
2,1,16,4000,35,1
3,2,20,5000,45,1
4,1,24,6000,77,0

In [ ]:
# Displaying row and column number
df.shape

(748, 5)

In [ ]:
print('Total Rows:', df.shape[0])
print('Total Columns:', df.shape[1])

Total Rows: 748
Total Columns: 5

In [ ]:
# Dataset Information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 748 entries, 0 to 747
Data columns (total 5 columns):
 #   Column                                      Non-Null Count  Dtype
---  ------                                      --------------  -----
 0   Recency (months)                            748 non-null    int64
 1   Frequency (times)                           748 non-null    int64
 2   Monetary (c.c. blood)                       748 non-null    int64
 3   Time (months)                               748 non-null    int64
 4   whether he/she donated blood in March 2007  748 non-null    int64
dtypes: int64(5)
memory usage: 29.3 KB

In [ ]:
# Finding Mean
df.mean()

Recency (months)                                 9.506684
Frequency (times)                                5.514706
Monetary (c.c. blood)                         1378.676471
Time (months)                                   34.282086
whether he/she donated blood in March 2007       0.237968
dtype: float64

In [ ]:
# Finding Median
df.median()

Recency (months)                                 7.0
Frequency (times)                                4.0
Monetary (c.c. blood)                         1000.0
Time (months)                                   28.0
whether he/she donated blood in March 2007       0.0
dtype: float64

In [ ]:
# Finding STD
df.std()

Recency (months)                                 8.095396
Frequency (times)                                5.839307
Monetary (c.c. blood)                         1459.826781
Time (months)                                   24.376714
whether he/she donated blood in March 2007       0.426124
dtype: float64

In [ ]:
# Finding Max
df.max()

Recency (months)                                 74
Frequency (times)                                50
Monetary (c.c. blood)                         12500
Time (months)                                    98
whether he/she donated blood in March 2007        1
dtype: int64

In [ ]:
# Finding Min
df.min()

Recency (months)                                0
Frequency (times)                               1
Monetary (c.c. blood)                         250
Time (months)                                   2
whether he/she donated blood in March 2007      0
dtype: int64

In [ ]:
#
df.describe()

,Recency (months),Frequency (times),Monetary (c.c. blood),Time (months),whether he/she donated blood in March 2007
count,748.000000,748.000000,748.000000,748.000000,748.000000
mean,9.506684,5.514706,1378.676471,34.282086,0.237968
std,8.095396,5.839307,1459.826781,24.376714,0.426124
min,0.000000,1.000000,250.000000,2.000000,0.000000
25%,2.750000,2.000000,500.000000,16.000000,0.000000
50%,7.000000,4.000000,1000.000000,28.000000,0.000000
75%,14.000000,7.000000,1750.000000,50.000000,0.000000
max,74.000000,50.000000,12500.000000,98.000000,1.000000

## Data Cleaning

In [ ]:
import pandas as pd
# Sample File
excel_df = pd.read_excel("/content/drive/MyDrive/LOCTEC/DAWP 2023/Datasets/for excel/Data-for-Practice.xlsx")
excel_df.head()

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Excel Data for Practice Free Download,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Sales Rep,Shift,Cost Price,Selling Price,Profit,Profit %,Commission,Weekday
3,NaN,2022-07-01 00:00:00,Ben,Night,1112.94,1288,NaN,NaN,NaN,NaN
4,NaN,2022-07-01 00:00:00,Jacob,Day,1095.5,1250.75,NaN,NaN,NaN,NaN

In [ ]:
# Renaming Columns
excel_df = excel_df.rename(columns={'Unnamed: 0':'Abia', 'Unnamed: 1': 'Anambara', 'Unnamed: 4':'Rivers'})
excel_df

,Abia,Anambara,Unnamed: 2,Unnamed: 3,Rivers,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Excel Data for Practice Free Download,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Date,Sales Rep,Shift,Cost Price,Selling Price,Profit,Profit %,Commission,Weekday
3,NaN,2022-07-01 00:00:00,Ben,Night,1112.94,1288,NaN,NaN,NaN,NaN
4,NaN,2022-07-01 00:00:00,Jacob,Day,1095.5,1250.75,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
86,NaN,2022-08-29 00:00:00,Jacob,Day,774.2,946.25,NaN,NaN,NaN,NaN
87,NaN,2022-08-30 00:00:00,Ben,Day,1350.48,1509.5,NaN,NaN,NaN,NaN
88,NaN,2022-08-30 00:00:00,Jacob,Night,1053.37,1136.25,NaN,NaN,NaN,NaN
89,NaN,2022-08-31 00:00:00,Ben,Night,1161.92,1237,NaN,NaN,NaN,NaN
90,NaN,2022-08-31 00:00:00,Jacob,Day,951.93,1136,NaN,NaN,NaN,NaN

## Checking for Missing Values

In [ ]:
# Sample Dataset
df = pd.read_csv('/content/drive/MyDrive/LOCTEC/DAWP 2023/Dataset2/Smartphone/smartphones.csv')
df.head()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.1,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.1,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.5,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.1,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.1,60,2,ios,12.0,12.0,0,2532,1170

In [ ]:
# Check missing values
df.isnull()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
976,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
977,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
978,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
979,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [ ]:
# Check missing values
df.isnull().sum()

brand_name                     0
model                          0
price                          0
avg_rating                   101
5G_or_not                      0
processor_brand               20
num_cores                      6
processor_speed               42
battery_capacity              11
fast_charging_available        0
fast_charging                211
ram_capacity                   0
internal_memory                0
screen_size                    0
refresh_rate                   0
num_rear_cameras               0
os                            14
primary_camera_rear            0
primary_camera_front           5
extended_memory_available      0
resolution_height              0
resolution_width               0
dtype: int64

In [ ]:
# Check missing values with notnnull
df.notnull()

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,False,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
976,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
977,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
978,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
979,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [ ]:
# Check missing values
df.notnull().sum()

brand_name                   980
model                        980
price                        980
avg_rating                   879
5G_or_not                    980
processor_brand              960
num_cores                    974
processor_speed              938
battery_capacity             969
fast_charging_available      980
fast_charging                769
ram_capacity                 980
internal_memory              980
screen_size                  980
refresh_rate                 980
num_rear_cameras             980
os                           966
primary_camera_rear          980
primary_camera_front         975
extended_memory_available    980
resolution_height            980
resolution_width             980
dtype: int64

## Remove Rows with Missing Values

In [ ]:
drop_rows = df.dropna()
drop_rows

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
42,apple,Apple iPhone SE 2020,39900,6.3,0,bionic,6.0,2.65,1821.0,1,...,64,4.70,60,1,ios,12.0,7.0,0,1334,750
46,asus,Asus ROG Phone 5s 5G,39999,8.7,1,snapdragon,8.0,2.90,6000.0,1,...,128,6.78,144,3,android,64.0,24.0,0,2448,1080
47,asus,Asus ROG Phone 6,71999,8.6,1,snapdragon,8.0,3.20,6000.0,1,...,256,6.78,165,3,android,50.0,12.0,0,2448,1080
48,asus,Asus ROG Phone 6 Batman Edition,72999,8.8,1,dimensity,8.0,3.20,6000.0,1,...,256,6.78,165,3,android,50.0,12.0,0,2448,1080
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [ ]:
# Dropping rows with NaN columns
drop_rows_with_cols = df.dropna(subset=['battery_capacity'])

drop_rows_with_cols

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
11,apple,Apple iPhone 13,62999,7.9,1,bionic,6.0,3.22,3240.0,1,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
12,apple,Apple iPhone 13 (256GB),72999,7.9,1,bionic,6.0,3.22,3240.0,1,...,256,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

### Filling Missing Values

In [ ]:
# Filling with specific value
fill_value = df.fillna(2)

fill_value

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,2.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,2.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [ ]:
# Filling with mean
df['battery_capacity'].fillna(df['battery_capacity'].mean(), inplace=True)
df

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.000000,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.000000,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.000000,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,4817.748194,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,4817.748194,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.000000,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.000000,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.000000,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.000000,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.000000,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [ ]:
# Filling with median
df['battery_capacity'].fillna(df['battery_capacity'].median(), inplace=True)
df

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,5000.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,5000.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

## Handling Duplicates

In [ ]:
# Checking for duplicates
duplicate_df = df.duplicated().sum()
duplicate_df

0

In [ ]:
# Checking for duplicates
duplicate_df = df.avg_rating.duplicated().sum()
print("Total duplicated ratings:", duplicate_df)

Total duplicated ratings: 949

In [ ]:
# Removing Duplicates
removed_dup_rows = df.drop_duplicates()
removed_dup_rows

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [ ]:
# Removing Duplicates
removed_dup_rows = df.drop_duplicates(subset=['avg_rating'])
removed_dup_rows

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
5,apple,Apple iPhone 12 (256GB),67999,7.6,1,bionic,6.0,3.10,NaN,0,...,256,6.10,60,2,ios,12.0,12.0,0,2532,1170
9,apple,Apple iPhone 12 Pro (256GB),119900,8.0,1,bionic,6.0,3.10,NaN,0,...,256,6.10,60,3,ios,12.0,12.0,0,2532,1170
11,apple,Apple iPhone 13,62999,7.9,1,bionic,6.0,3.22,3240.0,1,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
15,apple,Apple iPhone 13 Pro,119900,8.3,1,bionic,6.0,3.22,3095.0,1,...,128,6.10,120,3,ios,12.0,12.0,0,2532,1170
16,apple,Apple iPhone 13 Pro (1TB),147900,8.4,1,bionic,6.0,3.22,3095.0,1,...,1024,6.10,120,3,ios,12.0,12.0,0,2532,1170
19,apple,Apple iPhone 13 Pro Max (1TB),179900,8.6,1,bionic,6.0,3.22,4352.0,1,...,1024,6.70,120,3,ios,12.0,12.0,0,2778,1284
21,apple,Apple iPhone 14,65999,8.1,1,bionic,6.0,3.22,3279.0,1,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
22,apple,Apple iPhone 14 (256GB),75999,8.2,1,bionic,6.0,3.22,3279.0,1,...,256,6.10,60,2,ios,12.0,12.0,0,2532,1170
24,apple,Apple iPhone 14 Mini,69990,7.0,0,bionic,NaN,NaN,3500.0,1,...,128,5.42,60,2,ios,12.0,12.0,0,2340,1080
32,apple,Apple iPhone 14 Pro Max (1TB),182999,7.8,1,bionic,6.0,NaN,4323.0,1,...,1024,6.70,120,3,ios,48.0,12.0,0,2796,1290
35,apple,Apple iPhone 15,82990,7.2,0,bionic,NaN,NaN,3285.0,1,...,128,6.06,60,2,ios,50.0,13.0,0,2532,1170
40,apple,Apple iPhone 7s,52990,NaN,0,fusion,4.0,2.37,2230.0,0,...,32,4.70,60,1,ios,13.0,7.0,0,1334,750
41,apple,Apple iPhone 9,29990,6.1,0,bionic,6.0,2.65,2050.0,1,...,64,4.70,60,1,ios,12.0,7.0,0,1334,750
42,apple,Apple iPhone SE 2020,39900,6.3,0,bionic,6.0,2.65,1821.0,1,...,64,4.70,60,1,ios,12.0,7.0,0,1334,750
44,apple,Apple iPhone SE 4,49990,6.0,1,bionic,6.0,3.22,NaN,0,...,64,6.10,60,1,ios,12.0,11.0,0,1580,750
46,asus,Asus ROG Phone 5s 5G,39999,8.7,1,snapdragon,8.0,2.90,6000.0,1,...,128,6.78,144,3,android,64.0,24.0,0,2448,1080
48,asus,Asus ROG Phone 6 Batman Edition,72999,8.8,1,dimensity,8.0,3.20,6000.0,1,...,256,6.78,165,3,android,50.0,12.0,0,2448,1080
53,blackview,Blackview BV5200 Pro,8990,6.7,1,helio,8.0,2.30,5180.0,1,...,64,6.10,60,2,android,13.0,8.0,1,1560,720
54,blu,BLU F91 5G,14990,8.5,1,dimensity,8.0,2.40,5000.0,1,...,128,6.80,60,4,android,48.0,16.0,1,2460,1080
63,google,Google Pixel 2 XL,15990,6.9,0,snapdragon,8.0,2.35,3520.0,1,...,128,6.00,60,1,android,12.2,8.0,0,2880,1440
69,google,Google Pixel 6 Pro,54300,8.9,1,google,8.0,2.80,5003.0,1,...,128,6.71,120,3,android,50.0,11.0,0,3120,1440
71,google,Google Pixel 6A,29999,7.1,1,google,8.0,NaN,4410.0,1,...,128,6.14,60,2,android,12.2,8.0,0,2400,1080
83,honor,Honor Play 30,9999,6.8,1,snapdragon,8.0,2.20,5000.0,0,...,128,6.50,60,1,android,13.0,5.0,1,1600,720
90,huawei,Huawei Honor 9N,10949,6.6,0,kirin,8.0,2.36,3000.0,0,...,64,5.84,60,2,android,13.0,16.0,1,2280,1080
117,infinix,Infinix Hot 20i,9999,6.4,0,helio,8.0,2.00,5000.0,0,...,64,6.60,60,2,android,13.0,8.0,1,1612,720
188,leeco,LeEco S1 Pro,10999,6.5,0,tiger,4.0,1.80,5000.0,1,...,128,6.50,60,2,android,13.0,5.0,0,1600,720
257,nokia,Nokia C31,9499,6.2,0,unisoc,8.0,1.60,5050.0,1,...,32,6.74,60,3,android,13.0,5.0,1,1600,720

In [ ]:
# Checking for duplicates
duplicate_df = removed_dup_rows.avg_rating.duplicated().sum()
print("Total duplicated ratings:", duplicate_df)

Total duplicated ratings: 0

## Manipulating Datasets
* **iloc:** index-based selection
* **loc:** label-based selection

In [ ]:
# Viewing single column of entire row
df.iloc[:,1]

0                                Apple iPhone 11
1                        Apple iPhone 11 (128GB)
2                        Apple iPhone 11 Pro Max
3                                Apple iPhone 12
4                        Apple iPhone 12 (128GB)
                         ...
975                      Xiaomi Redmi Note 9 Pro
976    Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB)
977                  Xiaomi Redmi Note 9 Pro Max
978                                 ZTE Axon 30S
979                         ZTE Axon 40 Ultra 5G
Name: model, Length: 980, dtype: object

In [ ]:
# Viewing few rows of entire row
df.iloc[0:2,1]

0            Apple iPhone 11
1    Apple iPhone 11 (128GB)
Name: model, dtype: object

In [ ]:
# Viewing entire rows and columns
df.iloc[:,:]

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,Apple iPhone 11,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,Apple iPhone 11 (128GB),46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,Apple iPhone 11 Pro Max,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,Apple iPhone 12,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,Apple iPhone 12 (128GB),55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,Xiaomi Redmi Note 9 Pro,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,Xiaomi Redmi Note 9 Pro (4GB RAM + 128GB),14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,Xiaomi Redmi Note 9 Pro Max,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,ZTE Axon 30S,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,ZTE Axon 40 Ultra 5G,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

### loc

In [ ]:
# Viewing rows and columns by label

df.loc[1:3, 'model':'5G_or_not']

                     model   price  avg_rating  5G_or_not
1  Apple iPhone 11 (128GB)   46999         7.5          0
2  Apple iPhone 11 Pro Max  109900         7.7          0
3          Apple iPhone 12   51999         7.4          1

## Manipulating Datasets

In [ ]:
# Assigning Values
iPhone_df = df.copy()

iPhone_df['model'] = 'iPhone'

In [ ]:
iPhone_df

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,iPhone,38999,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,iPhone,46999,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,iPhone,109900,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,iPhone,51999,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,iPhone,55999,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,iPhone,13999,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,iPhone,14439,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,iPhone,16490,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,iPhone,19999,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,iPhone,61990,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

In [ ]:
# Using Lambda
lambda_func = lambda x: x*2
iPhone_df['price'] = iPhone_df['price'].apply(lambda_func)

In [ ]:
iPhone_df

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
0,apple,iPhone,155996,7.3,0,bionic,6.0,2.65,3110.0,0,...,64,6.10,60,2,ios,12.0,12.0,0,1792,828
1,apple,iPhone,187996,7.5,0,bionic,6.0,2.65,3110.0,0,...,128,6.10,60,2,ios,12.0,12.0,0,1792,828
2,apple,iPhone,439600,7.7,0,bionic,6.0,2.65,3500.0,1,...,64,6.50,60,3,ios,12.0,12.0,0,2688,1242
3,apple,iPhone,207996,7.4,1,bionic,6.0,3.10,NaN,0,...,64,6.10,60,2,ios,12.0,12.0,0,2532,1170
4,apple,iPhone,223996,7.5,1,bionic,6.0,3.10,NaN,0,...,128,6.10,60,2,ios,12.0,12.0,0,2532,1170
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
975,xiaomi,iPhone,55996,7.5,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,48.0,16.0,1,2400,1080
976,xiaomi,iPhone,57756,7.7,0,snapdragon,8.0,2.30,5020.0,1,...,128,6.67,60,4,android,48.0,16.0,1,2400,1080
977,xiaomi,iPhone,65960,8.0,0,snapdragon,8.0,2.30,5020.0,1,...,64,6.67,60,4,android,64.0,32.0,1,2400,1080
978,zte,iPhone,79996,8.2,1,snapdragon,8.0,3.20,4200.0,1,...,128,6.90,120,4,android,50.0,16.0,1,2460,1080
979,zte,iPhone,247960,8.9,1,snapdragon,8.0,3.00,5000.0,1,...,128,6.80,120,3,android,64.0,16.0,0,2480,1116

## Sorting

In [ ]:
# Ascending Order
df.sort_values(by='price')

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
497,realme,Realme C2s,3499,6.3,0,helio,8.0,2.00,4000.0,0,...,32,6.10,60,2,android,13.0,5.0,1,1560,720
199,lyf,Lyf Earth 2,3890,NaN,0,snapdragon,8.0,1.50,2500.0,0,...,32,5.00,60,1,android,13.0,13.0,1,1920,1080
198,lyf,Lyf Earth 1,3990,6.0,0,snapdragon,8.0,1.50,3500.0,0,...,32,5.50,60,2,android,13.0,5.0,1,1920,1080
170,itel,Itel A23 Pro,3999,NaN,0,spreadtrum,4.0,1.40,2400.0,0,...,8,5.00,60,1,android,5.0,2.0,0,480,854
183,jio,Jio Phone 3,4499,NaN,0,NaN,4.0,1.40,2800.0,0,...,64,5.00,60,1,android,5.0,2.0,1,1280,720
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
873,xiaomi,Xiaomi Mi Mix Alpha,199990,NaN,1,snapdragon,8.0,2.96,4050.0,1,...,512,7.92,60,3,android,108.0,NaN,0,2250,2088
91,huawei,Huawei Mate 30 RS Porsche Design,214990,NaN,1,kirin,8.0,2.86,4500.0,1,...,512,6.53,60,4,android,40.0,32.0,1,2400,1176
94,huawei,Huawei Mate 50 RS Porsche Design,239999,8.1,0,snapdragon,8.0,3.20,4700.0,1,...,512,6.74,120,3,other,50.0,13.0,1,2616,1212
909,xiaomi,Xiaomi Redmi K20 Pro Signature Edition,480000,8.8,0,snapdragon,8.0,2.80,4000.0,1,...,256,6.39,60,3,android,48.0,20.0,0,2340,1080
732,vertu,Vertu Signature Touch,650000,6.2,0,snapdragon,8.0,1.50,2275.0,0,...,64,4.70,60,1,android,13.0,2.0,0,1920,1080

In [ ]:
# Descending Order
df.sort_values(by='price', ascending=False)

,brand_name,model,price,avg_rating,5G_or_not,processor_brand,num_cores,processor_speed,battery_capacity,fast_charging_available,...,internal_memory,screen_size,refresh_rate,num_rear_cameras,os,primary_camera_rear,primary_camera_front,extended_memory_available,resolution_height,resolution_width
732,vertu,Vertu Signature Touch,650000,6.2,0,snapdragon,8.0,1.50,2275.0,0,...,64,4.70,60,1,android,13.0,2.0,0,1920,1080
909,xiaomi,Xiaomi Redmi K20 Pro Signature Edition,480000,8.8,0,snapdragon,8.0,2.80,4000.0,1,...,256,6.39,60,3,android,48.0,20.0,0,2340,1080
94,huawei,Huawei Mate 50 RS Porsche Design,239999,8.1,0,snapdragon,8.0,3.20,4700.0,1,...,512,6.74,120,3,other,50.0,13.0,1,2616,1212
91,huawei,Huawei Mate 30 RS Porsche Design,214990,NaN,1,kirin,8.0,2.86,4500.0,1,...,512,6.53,60,4,android,40.0,32.0,1,2400,1176
873,xiaomi,Xiaomi Mi Mix Alpha,199990,NaN,1,snapdragon,8.0,2.96,4050.0,1,...,512,7.92,60,3,android,108.0,NaN,0,2250,2088
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,jio,Jio Phone 3,4499,NaN,0,NaN,4.0,1.40,2800.0,0,...,64,5.00,60,1,android,5.0,2.0,1,1280,720
170,itel,Itel A23 Pro,3999,NaN,0,spreadtrum,4.0,1.40,2400.0,0,...,8,5.00,60,1,android,5.0,2.0,0,480,854
198,lyf,Lyf Earth 1,3990,6.0,0,snapdragon,8.0,1.50,3500.0,0,...,32,5.50,60,2,android,13.0,5.0,1,1920,1080
199,lyf,Lyf Earth 2,3890,NaN,0,snapdragon,8.0,1.50,2500.0,0,...,32,5.00,60,1,android,13.0,13.0,1,1920,1080
497,realme,Realme C2s,3499,6.3,0,helio,8.0,2.00,4000.0,0,...,32,6.10,60,2,android,13.0,5.0,1,1560,720

## Querying

In [ ]:
df2 = df['avg_rating'] <= 6.0
df2.sum()

12

In [ ]:
df3 = (df['avg_rating'] > 5.0) & (df['price'] < 5000)

df3.sum()

2